import { z } from "zod";

const projectStatusSchema = z.enum(["live-current", "live-stale", "local-verified", "in-progress"]);

const projectSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/),
  title: z.string().min(2),
  kicker: z.string().min(2),
  classification: z.enum(["Client work", "Personal work", "Concept work"]),
  status: projectStatusSchema,
  featured: z.boolean(),
  summary: z.string().min(30),
  overview: z.array(z.string().min(30)).min(1),
  challenge: z.string().min(30),
  role: z.string().min(10),
  solution: z.string().min(30),
  stack: z.array(z.string().min(1)).min(1),
  capabilities: z.array(z.string().min(10)).min(2),
  limitations: z.array(z.string().min(10)).min(1),
  cover: z.string().startsWith("/"),
  coverAlt: z.string().min(10),
  screenshots: z.array(z.object({
    src: z.string().startsWith("/"),
    alt: z.string().min(10),
    caption: z.string().min(10),
  })).min(1),
  repositoryUrl: z.string().url().optional(),
  liveUrl: z.string().url().optional(),
  evidence: z.array(z.string().min(3)).min(1),
}).superRefine((project, context) => {
  if (project.liveUrl && project.status !== "live-current") {
    context.addIssue({ code: "custom", path: ["liveUrl"], message: "Only a live-current project may expose a live URL." });
  }
});

const projectData = [
  {
    slug: "juaduka-pos",
    title: "JuaDuka POS",
    kicker: "Offline-first retail operations",
    classification: "Personal work",
    status: "in-progress",
    featured: true,
    summary: "An Android-first point-of-sale product built for the realities of small Kenyan retail shops, with resilient local workflows at its core.",
    overview: [
      "JuaDuka is an offline-first Flutter application for catalog, stock, checkout, customer debt and daily reporting. Core shop operations run locally on an encrypted SQLite database so a weak connection does not stop a sale.",
      "The current milestone is an internal-alpha package, not a public production release. The product also includes Django foundations for registration, subscription and provider-backed services that are intentionally separated from local shop operations.",
    ],
    challenge: "Design a dependable shop tool that keeps money, stock and debt records consistent on affordable Android hardware, including when connectivity is poor or absent.",
    role: "Product design, system architecture, Flutter and Django implementation, verification design, and technical documentation.",
    solution: "A local-first transaction engine with fixed-integer money, encrypted persistence, atomic stock changes, guarded sensitive actions, recoverable backups and explicit provider boundaries.",
    stack: ["Flutter", "Dart", "SQLCipher", "Django", "Django REST Framework", "Android"],
    capabilities: [
      "Products, categories, barcodes, images, stock-in, adjustments and cost correction.",
      "Persistent cart, scan-to-cart, cash, manual M-PESA, split tender and Deni workflows.",
      "Sale voids, debt repayments and reversals, reconciled reports and discounts.",
      "Encrypted backup and restore, CSV/PDF exports, PIN security and diagnostics.",
      "103 Flutter tests and 15 Django tests recorded as passing in the Day 21 ledger.",
    ],
    limitations: [
      "Live Daraja and SMS integrations are not active in this release.",
      "The final physical shop-day walkthrough, true 1–2 GB device gate and full eight-hour soak remain open.",
      "The available device screenshot records the Day 2 persistence milestone; current-flow screenshots still require a connected test device.",
    ],
    cover: "/projects/juaduka-logo.png",
    coverAlt: "JuaDuka POS horizontal logo on a dark background",
    screenshots: [{ src: "/projects/juaduka-day2-device.png", alt: "JuaDuka Day 2 encrypted database milestone on an Android device", caption: "Recorded Day 2 device evidence — retained as a milestone, not presented as the current full interface." }],
    repositoryUrl: "https://github.com/KeyNash/Juaduka-POS",
    evidence: ["README.md", "docs/day-21-status.md", "docs/day-21-spec-audit.md", "docs/21-day-roadmap.md"],
  },
  {
    slug: "nexa-mobile",
    title: "Nexa Mobile",
    kicker: "Production-minded phone commerce",
    classification: "Personal work",
    status: "local-verified",
    featured: true,
    summary: "A full-stack Kenyan phone storefront that keeps pricing, stock and payment state authoritative on the server.",
    overview: [
      "Nexa Mobile pairs a mobile-first Next.js storefront with a Django REST API for catalog, accounts, inventory, orders, tracking and administration.",
      "The implementation separates a convincing shopping journey from real-world operations: payment preferences create pending records until an actual provider callback can be verified.",
    ],
    challenge: "Build a credible commerce experience without allowing browser state to control prices, stock availability or payment completion.",
    role: "Product direction, interface design, full-stack implementation and verification.",
    solution: "A typed storefront backed by transaction-safe Django order creation, row-locked inventory checks and provider-ready payment boundaries.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Django", "Django REST Framework", "PostgreSQL-ready"],
    capabilities: [
      "Responsive catalog, product discovery, cart, checkout and order-tracking interfaces.",
      "Server-authoritative totals, atomic order creation and stock validation.",
      "Catalog, authentication, inventory, order, payment and Django Admin foundations.",
      "A locally verified synthetic order resolved through tracking as pending payment.",
    ],
    limitations: [
      "No public deployment is currently verified.",
      "M-PESA and card settlement require real provider credentials, callbacks and reconciliation testing.",
      "Product presentation does not imply an operating retailer, delivery network or warranty programme.",
    ],
    cover: "/projects/nexa-device.png",
    coverAlt: "Black smartphone used in the verified Nexa Mobile product catalog",
    screenshots: [{ src: "/projects/nexa-device.png", alt: "Black smartphone product image from the Nexa Mobile catalog", caption: "Repository-owned catalog asset. A current full-page build capture is pending the next local verification run." }],
    evidence: ["README.md", "docs/product-spec.md", "docs/polish-record.md", "docs/deployment.md"],
  },
  {
    slug: "tamu-kenya",
    title: "Tamu Kenya",
    kicker: "A transparent marketplace concept",
    classification: "Concept work",
    status: "local-verified",
    featured: true,
    summary: "A full-stack marketplace concept for an illustrative Kenyan pantry catalog, designed around clear product discovery and honest transaction boundaries.",
    overview: [
      "Tamu Kenya combines a Next.js storefront with a Django REST API for catalog, accounts, carts, addresses, inventory and pending order requests.",
      "Its products, prices, stock and stories are explicitly illustrative. The software demonstrates marketplace behavior without presenting itself as a retailer or accepting real payments.",
    ],
    challenge: "Explore a distinctly Kenyan marketplace experience while keeping fictional catalog content and dormant payment adapters unmistakably separate from live commerce.",
    role: "Product concept, interface direction, full-stack implementation and technical documentation.",
    solution: "A mobile-first catalog and checkout flow with server-authoritative totals, transactional stock updates and explicit pending-payment states.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Django", "Django REST Framework", "SQLite/PostgreSQL"],
    capabilities: [
      "Searchable and filterable catalog, variants, persistent cart and checkout review.",
      "Custom email-based accounts, address handling, cart merge and order APIs.",
      "Server-authoritative totals and transactional inventory updates.",
      "Dynamic metadata, sitemap, robots handling and responsive images.",
    ],
    limitations: [
      "The catalog and its regional stories are illustrative interface data.",
      "No payment provider is contacted and no money, delivery or fulfilment service is offered.",
      "A public live deployment is not currently verified.",
    ],
    cover: "/projects/tamu-hero.jpg",
    coverAlt: "Kenyan coffee beans and a cup used in the Tamu Kenya concept catalog",
    screenshots: [{ src: "/projects/tamu-hero.jpg", alt: "Coffee imagery from the Tamu Kenya illustrative catalog", caption: "Repository-owned concept imagery. A new full-page build capture is pending deployment preparation." }],
    repositoryUrl: "https://github.com/KeyNash/tamu-kenya",
    evidence: ["README.md", "docs/portfolio-spec.md", "frontend and backend source"],
  },
  {
    slug: "mamu-atelier",
    title: "MAMU Atelier",
    kicker: "Editorial fashion portfolio",
    classification: "Client work",
    status: "live-current",
    featured: true,
    summary: "An image-led digital home for emerging womenswear designer Mariam Yunus, built to present garments, process and an evolving brand system.",
    overview: [
      "MAMU Atelier uses an editorial multi-page structure to move between the designer story, brand language, collections and individual garment studies.",
      "The content layer is kept in typed local data so the portfolio can evolve without rewriting its view components.",
    ],
    challenge: "Create a refined fashion portfolio that gives supplied imagery room to lead while avoiding unsupported claims about the maturity or performance of the business.",
    role: "Front-end implementation and interface refinement demonstrated by the repository.",
    solution: "A responsive editorial system with typed content accessors, filterable work, statically generated detail pages and restrained progressive motion.",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion", "Vitest"],
    capabilities: [
      "Home, designer story, portfolio, garment detail, brand and contact routes.",
      "Typed JSON-backed content and statically generated portfolio entries.",
      "Responsive imagery, metadata, sitemap, robots rules and generated social imagery.",
      "Reduced-motion behavior and verified overflow protection across the recorded viewport matrix.",
    ],
    limitations: ["Business outcomes, sales, awards and testimonials are not claimed.", "Only repository-demonstrated front-end responsibilities are attributed to Nash."],
    cover: "/projects/mamu-desktop.webp",
    coverAlt: "MAMU Atelier editorial homepage featuring garments by Mariam Yunus",
    screenshots: [
      { src: "/projects/mamu-desktop.webp", alt: "Desktop view of the MAMU Atelier editorial homepage", caption: "Verified desktop build at 1440 pixels." },
      { src: "/projects/mamu-mobile.webp", alt: "Mobile view of the MAMU Atelier editorial homepage", caption: "Verified mobile build at 375 pixels." },
    ],
    repositoryUrl: "https://github.com/KeyNash/Mamu_Atelier_v1",
    liveUrl: "https://mamu-atelier-v1.vercel.app/",
    evidence: ["README.md", "CASE_STUDY.md", "VERIFICATION.md", "docs/screenshots"],
  },
  {
    slug: "anointed-rivers-ministry",
    title: "Anointed Rivers Ministry",
    kicker: "A clear multi-page ministry home",
    classification: "Client work",
    status: "live-current",
    featured: false,
    summary: "A responsive ministry website organizing services, beliefs, ministries, giving guidance and building-project updates into a consistent public experience.",
    overview: [
      "The site gives visitors clear routes to understand the ministry, plan a visit, explore ministries and contact leadership.",
      "Sensitive publishing details such as payment accounts, fundraising figures and social links remain subject to ministry confirmation rather than being invented for completeness.",
    ],
    challenge: "Turn a collection of ministry pages and photographs into a coherent, accessible site while protecting unconfirmed contact, giving and fundraising details.",
    role: "Front-end design, implementation and content-safety refinement demonstrated by the repository.",
    solution: "A shared visual system across five semantic pages, with responsive navigation, clear contact actions, gallery handling and page-specific metadata.",
    stack: ["HTML", "CSS", "JavaScript"],
    capabilities: ["Home, About, Ministries, Give and Building Project pages.", "Responsive navigation, service information, ministry sections and direct contact actions.", "Page-level metadata, sitemap and robots configuration."],
    limitations: ["Giving accounts, fundraising totals and external social destinations require ministry confirmation before reuse.", "No attendance, donation or growth outcomes are attributed to the website."],
    cover: "/projects/anointed-rivers-desktop.webp",
    coverAlt: "Desktop homepage of the Anointed Rivers Ministry website",
    screenshots: [
      { src: "/projects/anointed-rivers-desktop.webp", alt: "Desktop homepage of Anointed Rivers Ministry", caption: "Verified desktop homepage capture." },
      { src: "/projects/anointed-rivers-mobile.webp", alt: "Mobile homepage of Anointed Rivers Ministry", caption: "Verified mobile homepage capture." },
    ],
    repositoryUrl: "https://github.com/KeyNash/Annointed_Rivers_Ministry",
    liveUrl: "https://keynash.github.io/Annointed_Rivers_Ministry/",
    evidence: ["README.md", "docs/screenshots", "multi-page source"],
  },
  {
    slug: "legends-barber-beauty-spa",
    title: "Legends Barber & Beauty Spa",
    kicker: "Local service discovery and booking handoff",
    classification: "Personal work",
    status: "live-current",
    featured: false,
    summary: "A responsive single-page concept for an Eldoret barber and beauty business, focused on clear services, practical business information and honest booking handoff.",
    overview: [
      "Visitors can review service categories, operating details and prepare a booking request from one focused page.",
      "The form opens an addressed SMS draft and explicitly states that an appointment remains unconfirmed until the business responds.",
    ],
    challenge: "Create a useful booking journey without pretending that a local form is a real scheduling system.",
    role: "Interface design, front-end implementation and accessibility refinement.",
    solution: "A responsive editorial service site with date validation, an SMS handoff and clear confirmation boundaries.",
    stack: ["HTML", "CSS", "JavaScript"],
    capabilities: ["Service overview, shop information, responsive navigation and booking-request form.", "Date validation and a transparent SMS-based booking handoff.", "Visible focus, semantic structure and reduced-motion-aware reveal behavior."],
    limitations: ["The website does not create or confirm appointments.", "No customer volume, reviews or business outcomes are claimed."],
    cover: "/projects/legends-desktop.webp",
    coverAlt: "Desktop homepage of Legends Barber and Beauty Spa",
    screenshots: [
      { src: "/projects/legends-desktop.webp", alt: "Desktop view of the Legends service website", caption: "Verified desktop homepage capture." },
      { src: "/projects/legends-mobile.webp", alt: "Mobile view of the Legends service website", caption: "Verified mobile homepage capture." },
    ],
    repositoryUrl: "https://github.com/KeyNash/legends-barber-beauty-spa",
    liveUrl: "https://keynash.github.io/legends-barber-beauty-spa/",
    evidence: ["README.md", "docs/screenshots", "verify.mjs"],
  },
  {
    slug: "mahabu-media-services",
    title: "Mahabu Media Services",
    kicker: "A safer media-studio brief experience",
    classification: "Client work",
    status: "live-stale",
    featured: false,
    summary: "A responsive media-studio website that explains service capabilities and helps visitors prepare a structured project brief locally in their browser.",
    overview: [
      "The current repository focuses the experience on media capabilities, visual work and a transparent brief builder.",
      "The brief is not submitted or stored. Visitors can copy it and share it through a confirmed contact channel when one is available.",
    ],
    challenge: "Improve a media-services presentation while removing unsupported experience metrics, testimonials, client claims and fake form behavior.",
    role: "Front-end implementation and content-integrity refinement demonstrated by the repository.",
    solution: "A responsive studio presentation with a dependency-free local brief generator and clearly bounded contact behavior.",
    stack: ["HTML", "CSS", "JavaScript"],
    capabilities: ["Responsive capability sections and locally owned imagery.", "A structured project-brief generator that runs entirely in the browser.", "Semantic layout, focus treatment and reduced-motion-aware progressive reveal."],
    limitations: ["The public deployment contains older unsupported promotional claims and is intentionally not linked here.", "The current repository does not publish unconfirmed contacts, pricing, testimonials or client projects."],
    cover: "/projects/mahabu-desktop.webp",
    coverAlt: "Desktop capture of the refined Mahabu Media Services website",
    screenshots: [
      { src: "/projects/mahabu-desktop.webp", alt: "Desktop view of the current Mahabu Media Services build", caption: "Current verified local build; the older public deployment is intentionally withheld." },
      { src: "/projects/mahabu-mobile.webp", alt: "Mobile view of the current Mahabu Media Services build", caption: "Verified mobile capture of the current local build." },
    ],
    repositoryUrl: "https://github.com/KeyNash/Mahabu-media-services",
    evidence: ["README.md", "docs/screenshots", "verify.mjs"],
  },
  {
    slug: "chellah-nailed-it",
    title: "Chellah Nailed It",
    kicker: "Beauty work, presented without filler",
    classification: "Client work",
    status: "live-current",
    featured: false,
    summary: "An editorial beauty portfolio centered on Chellah’s nail, braid and loc work, with transparent prices and direct social booking routes.",
    overview: [
      "The redesign replaces generic stock presentation and unsupported claims with the business’s own visual work and known service information.",
      "Visitors can filter the gallery, inspect work in an accessible preview and continue to the confirmed social booking channel.",
    ],
    challenge: "Separate genuine business material from stock imagery, fabricated-looking testimonials and a booking form that previously simulated success.",
    role: "Front-end implementation and interface refinement demonstrated by the repository.",
    solution: "A React-based single-page portfolio with an accessible filtered gallery, clear pricing and direct booking handoff.",
    stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Lucide React"],
    capabilities: ["Filterable nails, braids and locs gallery with keyboard-dismissable image preview.", "Responsive navigation, visible focus and reduced-motion handling.", "Service prices, location wording and confirmed Instagram/TikTok routes from the source project."],
    limitations: ["No testimonials, review totals or years-in-business claims are presented.", "Instagram remains the primary booking route until another verified service is supplied."],
    cover: "/projects/chellah-desktop.webp",
    coverAlt: "Desktop view of the Chellah Nailed It beauty portfolio",
    screenshots: [
      { src: "/projects/chellah-desktop.webp", alt: "Desktop view of the Chellah Nailed It portfolio", caption: "Verified desktop production build." },
      { src: "/projects/chellah-mobile.webp", alt: "Mobile view of the Chellah Nailed It portfolio", caption: "Verified mobile production build." },
    ],
    repositoryUrl: "https://github.com/KeyNash/Chellah_nailed_it",
    liveUrl: "https://chellah-nailed-it.vercel.app/",
    evidence: ["README.md", "CASE_STUDY.md", "verification/screenshots"],
  },
  {
    slug: "koromosho-springs",
    title: "Koromosho Springs",
    kicker: "A Kenyan water-delivery interface concept",
    classification: "Concept work",
    status: "live-stale",
    featured: false,
    summary: "A personal interface concept for an Eldoret-first water delivery experience, using illustrative prices and transparent non-transactional interactions.",
    overview: [
      "Koromosho Springs explores a contemporary Kenyan visual language inspired by Rift Valley greens, wet stone, rich soil and woven texture.",
      "Its estimator creates a copyable sample brief but never claims to place an order, collect payment or represent an operating water company.",
    ],
    challenge: "Turn a generic bottled-water page into a locally specific portfolio concept while removing invented metrics, testimonials and operational claims.",
    role: "Concept direction, interface design and front-end implementation.",
    solution: "A responsive one-page experience with sample Kenyan-shilling pricing, concept delivery zones and an honest order estimator.",
    stack: ["HTML", "CSS", "JavaScript"],
    capabilities: ["Responsive navigation and a localized sample catalog.", "Interactive estimator with Kenyan-shilling formatting and a copyable demo brief.", "Semantic structure, visible focus and reduced-motion support."],
    limitations: ["The project is not an operating company and does not process real orders or payments.", "The older deployment contains unsupported business claims and is intentionally not linked here.", "Prices, products and delivery zones are illustrative."],
    cover: "/projects/koromosho-desktop.webp",
    coverAlt: "Desktop view of the Koromosho Springs Kenyan water concept",
    screenshots: [
      { src: "/projects/koromosho-desktop.webp", alt: "Desktop view of the current Koromosho Springs concept", caption: "Verified local concept build; the older public deployment is intentionally withheld." },
      { src: "/projects/koromosho-mobile.webp", alt: "Mobile view of the current Koromosho Springs concept", caption: "Verified mobile concept build." },
    ],
    repositoryUrl: "https://github.com/KeyNash/Kosromosho_Springs",
    evidence: ["README.md", "CASE_STUDY.md", "VERIFICATION.md", "assets/screenshots"],
  },
  {
    slug: "aura-kenya",
    title: "Aura Kenya",
    kicker: "An intentional dating product walkthrough",
    classification: "Concept work",
    status: "live-current",
    featured: false,
    summary: "A fictional, local-only dating product walkthrough exploring how intent, safety and a Kenyan sense of place can shape discovery and conversation.",
    overview: [
      "Aura Kenya is a personal product concept rather than a live dating service. Every profile, match and conversation in the public demo is fictional.",
      "The account-free experience demonstrates discovery, reactions, matches, local messaging and profile editing while keeping data inside the browser session.",
    ],
    challenge: "Design a warm adult dating experience without implying a real member community, operational moderation system or production-ready backend.",
    role: "Product concept, interface direction and front-end implementation.",
    solution: "A clearly labelled portfolio demo with versioned session state, fictional profiles and explicit product-safety boundaries.",
    stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Hono", "tRPC", "Drizzle ORM"],
    capabilities: ["Account-free demo journey across discovery, matches, messaging and profile editing.", "Fictional profiles, local session state, filters and clear empty states.", "Lazy-loaded routes, keyboard focus and reduced-motion handling.", "Backend authorization groundwork that derives identity from server context."],
    limitations: ["Aura Kenya is not a live dating service and has no real users or accounts.", "The backend requires production infrastructure, moderation, privacy and security review before activation.", "No payments, real-time presence or location sharing are implemented."],
    cover: "/projects/aura-desktop.webp",
    coverAlt: "Desktop homepage of the Aura Kenya product concept",
    screenshots: [
      { src: "/projects/aura-desktop.webp", alt: "Desktop view of the Aura Kenya fictional product demo", caption: "Verified desktop portfolio demo." },
      { src: "/projects/aura-mobile.webp", alt: "Mobile view of the Aura Kenya fictional product demo", caption: "Verified mobile portfolio demo." },
    ],
    repositoryUrl: "https://github.com/KeyNash/aura-kenya",
    liveUrl: "https://aura-kenya.vercel.app/",
    evidence: ["README.md", "CASE_STUDY.md", "VERIFICATION.md", "docs/screenshots"],
  },
] as const;

export type Project = z.infer<typeof projectSchema>;
export type ProjectStatus = z.infer<typeof projectStatusSchema>;

export const projects: Project[] = z.array(projectSchema).parse(projectData);

export const projectStatusLabels: Record<ProjectStatus, string> = {
  "live-current": "Live & verified",
  "live-stale": "Verified build · live link withheld",
  "local-verified": "Verified locally",
  "in-progress": "In active development",
};

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export const featuredProjects = projects.filter((project) => project.featured);
